### PR TITLE
Sprint3 -- Updated for Interacting with Timeline Post (Like, Share, Comment) 

### PR DESCRIPTION
**Pull request by michellehardin**
The current push has a working like post, share a friends post (or your own), and comment on a post.

### CODE REVIEW

**Comment by michellehardin** [comment]
Successfully fixed comment on post

**Comment by LordSheffield** [comment]
Looks good.

**Comment by Philip-Haggard** [comment]
Working as intended

**Review by Philip-Haggard — COMMENTED** [review]
Working as intended

**Pull request merged**
